modLoader="javafml"
loaderVersion="[31,)"
authors="Toureiffel"
license="GPL3"

[[mods]]
	modId="inst_red"
	version="1.0.2.0"
	displayName="Instant redstone"
	authors="Toureiffel"
	description="A mod adding instant redstone repeaters and torches"
	
	[[dependencies.inst_red]]
		modId="forge"
		mandatory=true
		versionRange="[32,)"
		ordering="NONE"
		side="BOTH"
	
	[[dependencies.inst_red]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.16.3]"
		ordering="NONE"
		side="BOTH"